object ViewDefault: TViewDefault
  Left = 0
  Top = 0
  Caption = 'ViewDefault'
  ClientHeight = 201
  ClientWidth = 447
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnClose = FormClose
  OnCreate = FormCreate
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
end
